#!/usr/bin/env bash
# registry.sh [dir]: write the fastapi inventory to <dir>/docs/inventory/fastapi.md.
# Output is deterministic (no timestamps) so re-running it on unchanged code gives no diff.
set -eu
dir=$(cd "${1:-.}" && pwd)
out=$dir/docs/inventory/fastapi.md
version=$(cd "$dir" && top=$(git rev-parse --show-toplevel 2>/dev/null) && jq -r '.kit_version // "unknown"' "$top/.agent-kit.json" 2>/dev/null) || version=unknown

# Python files inside a directory named $1, relative to dir, without virtualenvs and tests.
files() {
  (cd "$dir" && find . \( -name .venv -o -name venv -o -name .git -o -name tests -o -name __pycache__ \) -prune -o \
    -type f -path "*/$1/*.py" ! -name __init__.py -print | sed 's|^\./||' | LC_ALL=C sort)
}

# section <title> <dir name> <what to list: classes|functions|routes>
section() {
  echo "## $1"
  list=$(files "$2")
  [ -n "$list" ] || echo "_None yet._"
  printf '%s\n' "$list" | while IFS= read -r f; do
    [ -n "$f" ] || continue
    case "$3" in
      classes) items=$(grep -oE '^class [A-Z][A-Za-z0-9_]*' "$dir/$f" | awk '{print $2}') ;;
      functions) items=$(grep -oE '^[[:space:]]*(async )?def [a-z][a-z0-9_]*' "$dir/$f" | awk '{print $NF}') ;;
      routes) items=$(grep -oE '@[a-z_]+\.(get|post|put|patch|delete)\("[^"]*"' "$dir/$f" |
        sed -E 's/@[a-z_]+\.([a-z]+)\("(.*)"/\1 \2/' | awk '{print toupper($1), $2}') ;;
    esac
    items=$(printf '%s\n' "$items" | paste -sd, - | sed 's/,/, /g')
    echo "- \`$f\`${items:+: $items}"
  done
  echo
}

mkdir -p "$(dirname "$out")"
{
  echo "<!-- Generated by agent-kit $version from stacks/fastapi/registry.sh. Do not edit. -->"
  echo "# Inventory: fastapi"
  echo
  echo "Reuse these before creating anything new."
  echo
  section "Models" models classes
  section "Schemas" schemas classes
  section "Repositories" repositories functions
  section "Services" services functions
  section "Routers" routers routes
} > "$out"
echo "wrote $out"
