#!/usr/bin/env bash
# KIT-10: kit sync on a fake monorepo with frontend/ and backend/.
. "$(dirname "$0")/../lib.sh"

kit() { "$BASH" "$KIT/bin/kit" "$@"; }
p=$TMP/project
mkdir -p "$p/frontend/src/components/shared" "$p/backend/app/models"
git -C "$p" init -q
git -C "$p" config user.email t@example.com
git -C "$p" config user.name test

out=$(cd "$p" && kit sync 2>&1)
check "missing .agent-kit.json exits 1 with an example" '! (cd "$p" && kit sync >/dev/null 2>&1) && printf "%s" "$out" | grep -q "\"stacks\""'

echo '{"stacks": {"frontend": "nextjs", "backend": "fastapi"}}' > "$p/.agent-kit.json"
printf '# Frontend\n\nOur own notes.\n' > "$p/frontend/AGENTS.md"
printf 'export default function Card() {}\n' > "$p/frontend/src/components/shared/Card.tsx"
printf 'class Product(Base):\n    pass\n' > "$p/backend/app/models/product.py"

(cd "$p" && kit sync >/dev/null 2>&1)
check "sync exits 0" '[ $? -eq 0 ]'
for s in nextjs fastapi; do
  check "stack copy $s has all contract files" '[ -f "$p/.agent-kit/stacks/$s/rules.md" ] && [ -x "$p/.agent-kit/stacks/$s/verify.sh" ] && [ -x "$p/.agent-kit/stacks/$s/registry.sh" ] && [ -d "$p/.agent-kit/stacks/$s/lint" ]'
  check "stack copy $s carries generated headers" '! grep -L "Generated by agent-kit" -r "$p/.agent-kit/stacks/$s" | grep -q .'
done
check "frontend AGENTS.md has nextjs block" 'grep -qxF "<!-- agent-kit:begin nextjs -->" "$p/frontend/AGENTS.md" && grep -qxF "<!-- agent-kit:end nextjs -->" "$p/frontend/AGENTS.md"'
check "content outside markers kept" 'grep -q "Our own notes." "$p/frontend/AGENTS.md"'
check "backend AGENTS.md created with fastapi block" 'grep -qxF "<!-- agent-kit:begin fastapi -->" "$p/backend/AGENTS.md"'
check "inventories written" 'grep -q "Card" "$p/frontend/docs/inventory/nextjs.md" && grep -q "Product" "$p/backend/docs/inventory/fastapi.md"'
check "scripts/verify.sh generated and runs both stacks" '[ -x "$p/scripts/verify.sh" ] && grep -q "stacks/nextjs/verify.sh" "$p/scripts/verify.sh" && grep -q "stacks/fastapi/verify.sh" "$p/scripts/verify.sh"'
check "pre-commit hook installed" 'grep -q "scripts/verify.sh\" fast" "$p/.git/hooks/pre-commit"'
check "CLAUDE.md links next to each AGENTS.md" '[ "$(readlink "$p/frontend/CLAUDE.md")" = AGENTS.md ] && [ "$(readlink "$p/backend/CLAUDE.md")" = AGENTS.md ]'
check "gemini context file names" '[ "$(jq -c .context.fileName "$p/.gemini/settings.json")" = "[\"AGENTS.md\",\"GEMINI.md\"]" ]'
check "kit version recorded" '[ "$(jq -r .kit_version "$p/.agent-kit.json")" = "$(cat "$KIT/VERSION")" ] && [ "$(jq -r .kit_commit "$p/.agent-kit.json")" != null ]'

# Edit outside and inside the markers, then sync again.
printf '\nMore notes after the block.\n' >> "$p/frontend/AGENTS.md"
sed -i.bak 's/^### Components$/### Hand edited/' "$p/frontend/AGENTS.md" && rm "$p/frontend/AGENTS.md.bak"
git -C "$p" add -A && git -C "$p" commit --no-verify -qm snapshot
(cd "$p" && kit sync >/dev/null 2>&1)
check "edit inside the block is replaced" '! grep -q "### Hand edited" "$p/frontend/AGENTS.md" && [ "$(grep -c "agent-kit:begin nextjs" "$p/frontend/AGENTS.md")" = 1 ]'
check "notes outside the block survive" 'grep -q "Our own notes." "$p/frontend/AGENTS.md" && grep -q "More notes after the block." "$p/frontend/AGENTS.md"'
git -C "$p" add -A && git -C "$p" commit --no-verify -qm resync
(cd "$p" && kit sync >/dev/null 2>&1)
check "second sync produces no diff" '[ -z "$(git -C "$p" status --porcelain)" ]'

# An existing pre-commit hook is never overwritten.
q=$TMP/other
mkdir -p "$q/app"
git -C "$q" init -q
echo '{"stacks": {"app": "fastapi"}}' > "$q/.agent-kit.json"
printf '#!/bin/sh\necho mine\n' > "$q/.git/hooks/pre-commit"
out=$(cd "$q" && kit sync 2>&1)
check "existing pre-commit hook untouched" '[ "$(sed -n 2p "$q/.git/hooks/pre-commit")" = "echo mine" ]'
check "instructions printed instead" 'printf "%s" "$out" | grep -q "pre-commit hook already exists"'
finish
