#!/usr/bin/env bash
# registry.sh [dir]: write the nextjs inventory to <dir>/docs/inventory/nextjs.md.
# Output is deterministic (no timestamps) so re-running it on unchanged code gives no diff.
set -eu
dir=$(cd "${1:-.}" && pwd)
out=$dir/docs/inventory/nextjs.md
version=$(cd "$dir" && top=$(git rev-parse --show-toplevel 2>/dev/null) && jq -r '.kit_version // "unknown"' "$top/.agent-kit.json" 2>/dev/null) || version=unknown

# Source files, relative to dir, without dependencies, build output, tests, and stories.
files() {
  (cd "$dir" && find . \( -name node_modules -o -name .next -o -name .git \) -prune -o -type f -name "$1" -print |
    sed 's|^\./||' | grep -vE '\.(test|spec|stories)\.' | LC_ALL=C sort)
}

list_or_none() {
  if [ -n "$1" ]; then printf '%s\n' "$1"; else echo "_None yet._"; fi
}

ui=$(files '*.tsx' | grep '/components/ui/' | sed -E 's|.*/([^/]+)\.tsx$|- \1|' || true)
components=$(files '*.tsx' | grep '/components/' | grep -v '/components/ui/' | while IFS= read -r f; do
  name=$(grep -oE '^export (default )?(function|const) [A-Z][A-Za-z0-9]*' "$dir/$f" | head -1 | awk '{print $NF}')
  props=$(grep -oE '^(export )?(interface|type) [A-Za-z0-9]*Props' "$dir/$f" | head -1 | awk '{print $NF}')
  line="- ${name:-$(basename "$f" .tsx)}: \`$f\`"
  [ -n "$props" ] && line="$line (props: $props)"
  echo "$line"
done)
hooks=$(files 'use*.ts*' | grep '/hooks/' | sed 's|^|- `|; s|$|`|' || true)
lib=$(files '*.ts' | grep '/lib/' | sed 's|^|- `|; s|$|`|' || true)

mkdir -p "$(dirname "$out")"
{
  echo "<!-- Generated by agent-kit $version from stacks/nextjs/registry.sh. Do not edit. -->"
  echo "# Inventory: nextjs"
  echo
  echo "Reuse these before creating anything new."
  echo
  echo "## UI primitives (never recreate, import only)"
  list_or_none "$ui"
  echo
  echo "## Components"
  list_or_none "$components"
  echo
  echo "## Hooks"
  list_or_none "$hooks"
  echo
  echo "## Lib modules"
  list_or_none "$lib"
} > "$out"
echo "wrote $out"
