#!/usr/bin/env bash
# KIT-2: fresh install links every global item and merges hooks.
# shellcheck disable=SC2034 # variables are read inside the eval strings passed to check
. "$(dirname "$0")/../lib.sh"

run_install >/dev/null 2>&1
check "install exits 0" '[ $? -eq 0 ]'
check "claude context file" '[ "$(readlink "$HOME/.claude/rules/agent-kit.md")" = "$KIT/global/AGENTS.md" ]'
for f in "$KIT"/global/commands/*.md; do
  n=${f##*/}
  check "claude command $n" '[ "$(readlink "$HOME/.claude/commands/$n")" = "$f" ]'
  check "gemini command ${n%.md}.toml" 'head -1 "$HOME/.gemini/commands/${n%.md}.toml" | grep -q "Generated by agent-kit"'
done
check "gemini {{args}} placeholder" 'grep -q "{{args}}" "$HOME/.gemini/commands/spec.toml" && ! grep -q "\$ARGUMENTS" "$HOME/.gemini/commands/spec.toml"'
check "reviewer agent" '[ "$(readlink "$HOME/.claude/agents/reviewer.md")" = "$KIT/global/agents/reviewer.md" ]'
for d in "$KIT"/skills/*/ "$KIT"/vendor/skills/*/; do
  d=${d%/}
  n=${d##*/}
  check "skill $n (claude, gemini)" '[ "$(readlink "$HOME/.claude/skills/$n")" = "$d" ] && [ "$(readlink "$HOME/.gemini/skills/$n")" = "$d" ]'
done
check "gemini context file" '[ "$(readlink "$HOME/.gemini/GEMINI.md")" = "$KIT/global/AGENTS.md" ]'
check "hooks in settings.json" '[ "$(jq "[.hooks[][].hooks[].command] | length" "$HOME/.claude/settings.json")" = 3 ]'
check "hook commands point at kit" 'jq -r ".hooks[][].hooks[].command" "$HOME/.claude/settings.json" | grep -q "$KIT/global/hooks/protect-tests.sh"'
check "kit on ~/.local/bin" '[ "$(readlink "$HOME/.local/bin/kit")" = "$KIT/bin/kit" ]'
check "kit runs through the link" '"$BASH" "$HOME/.local/bin/kit" version | grep -q "agent-kit $(cat "$KIT/VERSION")"'
check "no backups on a fresh home" '[ ! -e "$HOME/.agent-kit-backup" ]'
finish
